# Main Config
baseURL = "https://manos-al-codigo.github.io/guia"
languageCode = "es-es"
title = "Manos al Código - Guía"
theme = "learn"
defaultContentLanguage = "es"

# Theme Specifics
[params]
  editURL = ""
  author = "Manos al Código"
  description = "Guía para el uso y modificación del sitio Manos al Código."
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableInlineCopyToClipboard = true
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = true
  disableBreadcrumb = false
  disableMermaid = true
  disableNextPrev = false
  themeVariant = "red"
  
  custom_css = ["css/sidebar.css", "css/misc.css"]

# Search Functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

# Sidebar Links
[[menu.shortcuts]] 
  name = "<i class='icon fas fa-globe-americas'></i> Sitio Principal"
  identifier = "main-site"
  url = "https://manos-al-codigo.github.io/"
  weight = 1

[[menu.shortcuts]] 
  name = "<i class='icon fab fa-youtube'></i> Canal de YouTube"
  identifier = "yt-channel"
  url = "https://www.youtube.com/channel/UCrqwe8J9W_WK5LkRJKWh7DA"
  weight = 2

[[menu.shortcuts]] 
  name = "<i class='icon fab fa-github'></i> GitHub Organization"
  identifier = "github-org"
  url = "https://github.com/manos-al-codigo"
  weight = 3